# Generated by Django 4.0 on 2022-01-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fulbari', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_username',
            new_name='username',
        ),
    ]
