# Generated by Django 4.0 on 2022-02-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fulbari', '0002_rename_customer_username_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
