# Generated by Django 4.0 on 2022-02-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fulbari', '0003_product_delete_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_tbl',
        ),
    ]
