# Generated by Django 4.0 on 2022-02-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fulbari', '0004_alter_product_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
