# Generated by Django 4.0 on 2022-02-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fulbari', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=200)),
                ('blog_details', models.CharField(max_length=200)),
                ('blog_image', models.FileField(upload_to='blog_image')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
